[package]
name = "aws-cloudflare-whitelist"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
aws-config = "0.54.1"
aws-sdk-ec2 = "0.24.0"
reqwest = "0.11.14"
